---
title: "David Martínez-Galicia"
about:
  template: trestles
  image-width: 10em
  links: 
    - text: LinkedIn
      url: "https://www.linkedin.com/in/dmgalicia/"
    - text: Twitter
      url: "https://twitter.com/OyeDavidGalicia"
    - text: GitHub
      url: "https://github.com/dmgalicia"
    - text: Email
      url: "mailto:dvdmtzglc@gmail.com"
comments: false
---

::: column-page
### Formación académica / Academic formation

-   Doctorado en Inteligencia Artificial, 2020-2024. Universidad Veracruza, Xalapa, México.
-   Maestría en Inteligencia Artificial, 2018-2020. Universidad Veracruza, Xalapa, México.
-   Licenciatura en Mecatrónica, 2012-2016. Universidad de Xalapa, Xalapa, México.

### Cursos / Courses

-   Desarrollo de Recursos Académico-Metodológicos para el Proceso de Titulación en la Educación Superior, 2023. Universidad de Xalapa.
-   Data Science Courses: R basics, Visualizations, Probabilistics, 2021. HarvardX, edX.

### Certificaciones / Certifications

-   TOEFL ITP, ETS. Score: 613. Obtainment: 12/15/2021. Expiration: 12/16/2023.
-   CompTIA Strata IT fundamentals, CompTIA. Obtainment: 06/16/2011. No expiration.

### Experiencia Docente / Teaching

-   Universidad Veracruzana, 2023.
    -   *Inteligencia Artificial Aplicada a la Ingeniería de Software.*
-   Universidad de Xalapa, 2022-2023.
    -   *Reconocimiento de patrones.*
    -   *Agentes Inteligentes.*
    -   *Estructuras de datos y programación.*
-   Instituto Mayor de Veracruz, 2017-2018.
    -   *Estadística.*
    -   *Informática básica.*

### Eventos acádemicos / Academic events

-   Facilitador,Taller Introducción a la ciencia de datos, Universidad de Xalapa, 2023.
-   Speaker, International Seminar of Computational Intelligence, 2021.
-   Speaker, Workshop on New Trends in Computational Intelligence and Applications, 2019.
-   Speaker, 7th International Workshop on Numerical and Evolutionary Optimization, 2019.
-   Ponente, IX Foro Internacional de Divulgación Científica y Tecnológica, 2019.

### Gestión académica / Academic Experience

-   Experto en contenido para diseño instruccional, Universidad de Xalapa, 2020.
    -   *Lenguajes de programación.*
    -   *Programación de dispositivos móviles.*
    -   *Temas selectos de Inteligencia Artificial.*
:::
