---
format: 
  html:
    toc: true
    toc-depth: 4
---

## Publications

#### 2022

\[[DOI](https://doi.org/10.1007/978-3-031-08266-5_27){target="_blank"}\] **Martínez-Galicia, D.**, Guerra-Hernández, A., Limón, X., Cruz-Ramírez, N., & Grimaldo, F. (2022). Extension of windowing as a learning technique in artificial noisy domains. *Studies in Computational Intelligence*, 443--457. https://doi.org/10.1007/978-3-031-08266-5_27

#### 2021

\[[PDF](publications/Chapter-PensamientoComputacionalMexico.pdf){target="_blank"}\] **Martínez-Galicia, D.**, Roldán-Ahumada, J. A., Quiroz-Castellanos, M. (2021). ¿Cómo resolver problemas de Optimización Combinatoria ayuda a desarrollar el Pensamiento Computacional? *Pensamiento Computacional en México*, 3--25.

#### 2020

\[[PDF](publications/Article-mca2020.pdf){target="_blank"}\] **Galicia, D.**, Guerra-Hernández, A., Cruz-Ramírez, N., Limón, X., & Grimaldo, F. (2020). Towards Windowing as a Sub-Sampling Method for Distributed Data Mining. *Research in Computer Science, 149*, 57-64.

\[[PDF](publications/article-rsc2020.pdf){target="_blank"}\] **Martínez-Galicia, D.**, Guerra-Hernández, A., Cruz-Ramírez, N., Limón, X., & Grimaldo, F. (2020). Windowing as a Sub-Sampling Method for Distributed Data Mining. *Mathematical and Computational Applications*. 25 (3): 39. https://doi.org/10.3390/mca25030039
